### ISSUE TITLE
[ZS] Lacerator class description shows climb wall ability

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#1]
![image](https://user-images.githubusercontent.com/10659238/40255050-67f1d1bc-5aab-11e8-99db-2dc31ab964c6.png)

Secondary shows Lunge / Climb Wall when current lacerator variant can only pounce with secondary.

**Comment by Raox2** [comment]
That description is the old description...does it seem wrong?

**Comment by ritzbits** [comment]
Updated issue description. Lacerators are not able to climb walls.

SECONDARY: Lunge / Climb wall -> SECONDARY: Lunge

minor change

**Comment by ritzbits** [comment]
Raox2
[sunrust-zs:master] 2 new commits
e9e261f Fixed lacerator descriptions. - Raox2
4e226c3 Fixed lua error - Raox2
