### ISSUE TITLE
[ZS] More fps loss per env_projectedtexture created

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#12]
env_projectedtexture consumes fps in the following categories:

- Flashlight Models
 can be disabled with "r_flashlightdepthtexture 0" or Shadow settings set to Low or Medium.
Translucent models do not have flashlight models.
- World Rendering and Brush Model Rendering
On certain maps, env_projectedtexture can cause the cost of World Rendering and Brush Model Rendering to spike up unusually high, ex. zs_onett.

- Shadow Rendering and Flashlight shadows
An engine feature designed to cut the env_projectedtexture was intentionally disabled, r_flashlightscissor (toggling it doesn't work).
This causes the env_projectedtexture to overdraw it's shadow more than it should in the current scene.
The issue was reported. https://github.com/Facepunch/garrysmod-issues/issues/3482

--------------------------------------------------------------------------------------

There should only ever be one use of env_projectedtexture, which is the player's flashlight.

If it really is a requirement for Manhacks to keep it, then if possible it should only be created clientside for the owner. Looks like such a feat is achievable -[ Advanced Light Entities](https://steamcommunity.com/sharedfiles/filedetails/?id=493751477)

> 2017/3/2
> Added "new" versions of the projected light and expensive light that use client-side objects instead of networked entities. They have a few missing features, but are less network-intensive and possibly less expensive.

**Comment by ghost** [comment]
Could you look into this? the request to fix the r_flashlightscissor issue has hit a dead end.

**Comment by ghost** [comment]
Does "entity:SetPreventTransmit( ply, true )" work in this case?
Preferably tied to an option in Performance.

**Comment by Raox2** [comment]
Serverside

**Comment by ghost** [comment]
I've not been looking into the issue properly, you're supposed to use, [Projectedtexture](http://wiki.garrysmod.com/page/Global/ProjectedTexture), which is the clientside version of env_projectedtexture.

I tested with that example code on the wiki, and put it into manhack/cl_init and commented out the env_projectedtexture in init, it works just fine.

It would need to be expanded upon though, to set the way it's [projected](http://wiki.garrysmod.com/page/Category:ProjectedTexture), and to only draw for the owner/zombies, or anyone who wants to toggle other players projectedtextures on.

**Comment by Raox2** [comment]
Let me know if the performance issues on onett and maps like that are improved. A new clientside projected texture is being used for flash lights.
