### ISSUE TITLE
[ZS] util.CreatePulseImpactEffect should be used sparingly

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#13]
[util.CreatePulseImpactEffect](https://github.com/JetBoom/zombiesurvival/search?q=util.CreatePulseImpactEffect&unscoped_q=util.CreatePulseImpactEffect)

Affects fps in Particle Rendering. 

This effect should used sparingly for the following weapons
- weapon_zs_z9000
- weapon_zs_hurricane
- weapon_zs_pulserifle
- weapon_zs_oberon
- weapon_zs_powerfists
- weapon_zs_oberon
- Include any that were added since the public release.

1. Limit the effect to bullets/attacks which successfully kill by targeting the head hitbox.
2. Only create the effect client side for the attacker and victim.
3. Modify scale/magnitude/radius to acceptable values, make it smaller perhaps, and with a lower lifetime.

**Comment by ritzbits** [comment]
[sunrust-zs:master] 1 new commit
bc31493 Replaced the pulse impact effect with less sparkly one. - Raox2

combine ball bounce -> AR2 impact
