### ISSUE TITLE
[ZS] Client-side effects manager

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#14]
1. Effects created from entities you own, status effects added to yourself or ones you create as the attacker should not be counted towards max effects rendered per frame.

2. Effects created or owned by others should count towards max effects rendered per frame, 
this includes the following:

- Projectiles
- Status effects (includes negative status effects given to by certain zombie attacks)
- Lua blood effects (include engine blood effects if possible)
- Other Particle effects, such as deployable's smoke damage.
- Decals

When choosing what to render, always give priority to effects which are closest to the local player.

3. Effects created from zombie projectiles must always render and should not be counted towards max effects rendered.

4. May need to impose limits on Chem Burster  explosion effect and status_bursterambience.

5. Make "Max Effects rendered" a slider option, 0 for unlimited.

----------------------------------------------------------------------------------------------------------

### GM:EndRound

Additional removals to GM:EndRound
- Active effects created from prop_* and status_* should be removed/disabled.
- util.RemoveAll('env_fire')
- util.RemoveAll('zombiegasses')

--------------------------------------------------------------------------------------------------------

Various other things I would like to see happen:

- Option to disable rendering status effects in world.
- Option disable drawing prop_playergib.
- Disable drawing ~~med darts and~~ oxygen tank.

**Comment by Raox2** [comment]
It's not feasible to track who owns effects, as far as I can see. They're sort of lost to the ether when they're created.

**Comment by ghost** [comment]
Would the next best thing be to track which team?

**Comment by Raox2** [comment]
Yes, because they inherently have teams in a lot of cases just by nature of
projectile.

**Comment by ghost** [comment]
Closed as it may not be needed.
Wasteful fps effects and draw calls can be tackled individually, rather than in a monolithic implementation.

If this is still needed, I may re-post in the suggestions github with a rewrite.
