### ISSUE TITLE
[ZS] Prevent pain sounds replaying until they're finished

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#16]
Guns which are can fire multiple bullets in quick succession, the zombie shouldn't replay pain sounds until they actually finish.

Mainly noticeable with Poison Zombie.

**Comment by ritzbits** [comment]
Raox2
[sunrust-zs:master] 1 new commit
b6ee52b Added the ability to adjust a zombie delay between pain noises

Poison zombies don't spam pain sounds as often. - Raox2


If not resolved : re-open
