### ISSUE TITLE
[ZS] Remove collisions from particles that don't need it

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#19]
Particles with the following "[particle:SetCollide(true)](https://github.com/JetBoom/zombiesurvival/search?p=4&q=particle%3ASetCollide%28true%29&unscoped_q=particle%3ASetCollide%28true%29)", cause fps loss in Particle Simulation.
Particles which have an origin point from a model or world shouldn't have a need for collisions.
There may be other cases where they aren't needed or are just pointless.

Examples:
Chem Burster [status_bursterambience](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/entities/entities/status_bursterambience/cl_init.lua#L48), which is spammable due to being attached to a zombie class.

Smoke damage from [prop_gunturret](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/entities/entities/prop_gunturret/cl_init.lua#L92) and it's variants.

prop_obj_sigil - this one seems pointless to me, and since sigils are set to transmit_always, I've seen that they still get culled, but it's not as reliable as other entities are.

prop_creepernest, same deal as the sigil.

zombiegasses

Some particles actually need it, as it's part of their effect to collide with the world and leave behind decals, most are just placing unnecessary burden on the client for little benefit.

**Comment by ritzbits** [comment]
Raox2
[sunrust-zs:master] 1 new commit
3c09cb4 Another quick fix and remove particle collision from a few things - Raox2

Particle collisions removed from prop_creepernest, prop_gunturret, prop_obj_sigil, status_chemzombieambience, zombiegasses
