### ISSUE TITLE
Resupply bug

### ISSUE THREAD

**Issue by MAVISSSSS** [Raox2/sunrust-issues#2]
When you select an ammo type and click it again to unselect it, it doesn't unselect it for resupply ammo type, even though the ammo type on the resupply says it's (resupply ammo type), it'll resupply the ammo type you just unselected.

Steps to recreate
- select ammo type in alt menu
- unselect ammo type
- resupply ammo
- get the ammo you deselected previously

**Comment by Raox2** [comment]
This should be fixed now.
