### ISSUE TITLE
[ZS] Interpenetrating entities - Players break elevator collision on death sometimes

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#21]
func_tracktrain
func_movelinear

On death the player stays at the position they're at with no collision, while the moving platform continues upward or which ever way gets into the players collision box, during this moment the player makes a full transition into a zombie, and then regains collision causing interpenetrating entities.

Using developer 2 for debug messages.
zs_serious_sam_arena
> Interpenetrating entities! (player and func_movelinear)

I get a different message with func_tracktrain on vertigo and lambdacore.
> Ignoring player blocking train!

I've observed status_knockdown on humans does not cause the interpenetrating entities issue.
The player is still carried along on moving platforms with no issue.

If possible, the player should be made to, never lose collision in the moment of death and transition.

If you were to set the movetype to noclip, it would have to be long enough so the moving platform can pass through the player before changing it back.

**Comment by ritzbits** [comment]
https://github.com/JetBoom/noxiousnet-issues/issues/126#issuecomment-257356544
> Noclip movetype doesn't work as fix. You still get this in console. I'd have assume it still would happen.

**Comment by Raox2** [comment]
As far as I can tell it's a weird source issue related the way collision groups proliferate.

**Comment by ghost** [comment]
Would it be possible to respawn the player instantly into fresh dead, leaving no time for loss of collision, while keeping the transition (revival) time the same?

I'm not sure what a viable solution would be, but as long as the player doesn't lose collision with the func_tracktrain/movelinear, it should solve the problem.

**Comment by ghost** [comment]
Are you able to detect ground type and prevent the "human to zombie transition" from occuring?

I guess it is indeed a source engine issue, however, the way zombie survival handles being killed from a zombie, exposes the flaw.

**Comment by sunrust-serv** [comment]
What kinda ground types does it happen on exactly? Is there something I could like easily look for

**Comment by ghost** [comment]
func_movelinear and func_tracktrain.

It happens when humans and zombies collide with each other, and during that if they are obstructing a func_movelinear/tracktrain, that's when collision is temporarily lost.

In the vertigo scenario, a player dies within a group of humans, that player loses collision, and then regains it as a fresh dead, causing other human players to get stuck, while the elevator moves upwards.
The moment the fresh dead is spawned, is the moment where "interpenetrating entities" occurs, the fresh dead in turn causes the opposing team to get stuck within itself, and then they too obstruct the elevator.

The following then causes temporary collision loss for the func_tracktrain/movelinear.

To put it simple, it's when 2 teams with different collision groups, are interpenetrating a func_tracktrain and func_movelinear.

My previous post about making sure it doesn't lose collision wouldn't have solved it.

**Comment by sunrust-serv** [comment]
is this after the slump has finished? Like after they're getting up or as soon as they start getting up

**Comment by ghost** [comment]
Edit: It happens the moment they die.

I've been trying to replicate it to no avail, I cannot cause the other human players to lose collision.
On vertigo the humans are carried on upwards while the fresh dead is sliding downwards.

For now, I'll just close this, and re-open if another instance of it happens on the live server.
