### ISSUE TITLE
[ZS] Lower cost of light cache

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#22]
Use r_drawlightcache 2 to see if there are more entities which don't necessarily need any lighting.

Add [render.SuppressEngineLighting(true)](https://wiki.garrysmod.com/page/render/SuppressEngineLighting) to props or anything that doesn't need it.
As an example, prop_nail is plentiful in games, so lighting should be turned off for them.

Where I think lighting should be disabled:
- prop_weapon
- prop_ammo
- prop_ffemitter base
- prop_nail
- prop lighting for status_human_holding
- clientside props from headshot kills
- entities which become transparent or only while transparent, includes zs_transparencyradius
 Manhack, Gunturret, Drones, Rollermines etc.
- props used in projectiles.

The swep code uses an alias of this, for each attached world model "surpresslightning = true" should be set.

weapon_zs_spinfusor (before)
![20180606233958_1](https://user-images.githubusercontent.com/39219459/41068785-0c7e6dc6-69e3-11e8-9059-922c50cb69a7.jpg)

weapon_zs_spinfusor (after)
![20180606233906_1](https://user-images.githubusercontent.com/39219459/41068809-22ffd008-69e3-11e8-9162-5d8f3497ffc7.jpg)

I don't think the view model is anything to worry about, but I think there should at least be options to disable lighting for just about anything.

This would cut down a lot on light cache, it would improve performance if you render a lot of players with their weapons, which is something you're forced to render when you're a zombie.

It would also help everyone in general, because each entity has a cost in light cache, moving entities cost more.

**Comment by Raox2** [comment]
The swep code uses an alias of this, for each attached world model "surpresslightning = true" should be set.

That would probably make them look bad

**Comment by ghost** [comment]
Light cache can be cut down from entities in the gamemode and the map in combination.

### Map
The map should have sources of light spread out, so that no entity calculates light from more than one light source in close proximity.

Only have one source of global lighting originating from sun/moon.

### Gamemode
The gamemode can disable light cache entries on entities where and/or when it's not needed.

### Commands
r_drawlightcache 0/1 - Draw light cache entries./2 - Draw rays.
r_visualizelighttraces 0/1 - Shows traces for lighting.

**Comment by ghost** [comment]
> Raox: Added a new option to disable weapon world models from being lit

>[sunrust-zs:master] 1 new commit
> 8a2a491 Disabled the lighting on a few entities that do... - Raox2
