### ISSUE TITLE
[ZS] Most models are not precached

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#23]
Since loading isn't an async process, it causes hitches/micro freeze in the game's rendering thread.
In zs, this happens for everything that uses a model.

- Weapons
View models and c__arms_*
World models (includes attached models)
Junk pack props
Props used in some projectiles
Props used in some effects

- Deployables
Attached models (if any)
Clientside props/debris

- Other models used in
prop_obj_sigil - props_wasteland/medbridge_post01.mdl
prop_obj_exit
prop_creepernest - props_wasteland/antlionhill.mdl
prop_playergib

zs does have a [precache function](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/gamemode/shared.lua#L466-L477), but it doesn't cover everything the gamemode uses.

I've seen that [TTT precaches weapons view and world models](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/weaponry.lua#L503-L512), and wish to see precaching in zs expanded to cover everything the gamemode uses.

developer 2 shows the following:

Client
>Loading: models/weapons/c_arms_citizen.mdl
Loading models/weapons/c_arms_citizen.mdl
Loading virtual model for weapons/c_arms_citizen.mdl
Loading: models/weapons/w_snip_scout.mdl
Loading models/weapons/w_snip_scout.mdl
Loading: models/weapons/w_supershorty.mdl
Loading models/weapons/w_supershorty.mdl
Loading: models/weapons/w_pist_p228.mdl
Loading models/weapons/w_pist_p228.mdl
Loading: models/weapons/w_rif_famas.mdl
Loading models/weapons/w_rif_famas.mdl
Loading: models/weapons/cstrike/c_pist_p228.mdl
Loading models/weapons/cstrike/c_pist_p228.mdl
Loading: models/weapons/v_supershorty/v_supershorty.mdl
Loading models/weapons/v_supershorty/v_supershorty.mdl
Loading: models/weapons/cstrike/c_snip_scout.mdl
Loading models/weapons/cstrike/c_snip_scout.mdl
Loading: models/weapons/cstrike/c_rif_famas.mdl
Loading models/weapons/cstrike/c_rif_famas.mdl

Server
![server](https://user-images.githubusercontent.com/39219459/41189672-8eaeb96c-6bc9-11e8-808b-c442da22ae06.png)

Everytime a level changes, this usually starts the loading process all over again.

**Comment by besenyei** [comment]
Woops nevermind

**Comment by Raox2** [comment]
It's a pretty monumental task since it would have to be, pretty much all manual.

**Comment by ritzbits** [comment]
Raox2
[sunrust-zs:master] 1 new commit
b429d62 Quickly run over weapon models and precache those. - Raox2


If not resolved : re-open

**Comment by Raox2** [comment]
Not resolved, there's a lot to do.
