### ISSUE TITLE
[ZS] entities ignore culling from area portal and/or visleaf

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#3]
Where props actually get culled, the same is not the case for most zs entities.
Some stayed visible when the area portal should've culled them, and some became visible in a visleaf where it shouldn't.

https://my.mixtape.moe/tnjovw.webm

Props which exhibited the issue:

- prop_rollermine
- prop_drone
- prop_manhack
- prop_spotlamp
- prop_ffemitter
- prop_gunturret
- prop_arsenalcrate
- prop_resupplybox
- projectile_impactmine

Afaik, Repair Field, Aegis Boards and Zapper aren't affected.

I haven't gone through the entire list of entities.

If more testing is required, I can easily replicate the issue on other maps.
[zs_abandoned_mall_v9](https://steamuserimages-a.akamaihd.net/ugc/911296191720304505/820F076F7440E69F5C3D8F79A194753062C8F449/)

**Comment by Raox2** [comment]
My current theory is entities with render bounds seem to be bypassing those visibility checks. I'll probably remove the render bounds, it's likely making things worse if anything.

**Comment by ghost** [comment]
- prop_remantler
- prop_obj_sigil

Close this when majority of/all entities obey engine visibility checks.

**Comment by ghost** [comment]
- Nightmare ignores culling from func_areaportal

I'll try and check the other classes, but this process is tedious.

**Comment by ghost** [comment]
If certain classes can ignore culling from area portals or visleaf, it might just be a side effect to [status_overridemodel](https://github.com/Raox2/sunrust-issues/issues/8).

I believe this issue for the most part has been dealt with.
