### ISSUE TITLE
[ZS] pointless creation of dummy_chemzombie

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#33]
[Chem Zombie L76-80](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/gamemode/zombieclasses/chem_zombie.lua#L76-L80)

```lua
	hook.Add("InitPostEntityMap", "MakeChemDummy", function()
		DUMMY_CHEMZOMBIE = ents.Create("dummy_chemzombie")
		if DUMMY_CHEMZOMBIE:IsValid() then
			DUMMY_CHEMZOMBIE:Spawn()
		end
```

Just realized what it's for.
Even though the class is unused, that code is still ran.

**Comment by Raox2** [comment]
If Chem Zombie comes back, there will be new code to replace it...but ultra low priority.
