### ISSUE TITLE
[ZS] status_zombiespawnbuff - clientside effect doesn't wear off in some cases

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#35]
> Jahmackat: I still apear as if i am in z-gas but i am not, also people can still shoot me
> ![image](https://cdn.discordapp.com/attachments/440916895336759296/460173549953351681/wtf.png)
> PriZm: I've seen this bug before many times as well

It seems to occur when the client is loading in and spawns on a nest.
It can also persist over to the human player, if the player joins on the zombie team, at the moment the round restarts and the player is respawned onto the human team.

> Wang:
> ![image](https://cdn.discordapp.com/attachments/448130224018685963/461035341999112192/ghost3.PNG)

These situations can be replicated if you forced a full update by starting a demo recording.

**Comment by ghost** [comment]
Could it have something to do with [self.DieTime](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/entities/entities/status_zombiespawnbuff.lua#L28) ?

**Comment by Raox2** [comment]
About to say no but I realised this is also being set clientside, it should be completely serversided in terms of duration.
