### ISSUE TITLE
[Sparkwerk] Dev server sending map change messages

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#41]
chieftuktuk - Last Saturday at 9:27 PM
seems like it shows map changes in the dev server
in #game-servers-info

**Comment by ritzbits** [comment]
> GitHubBOT08/15/2018
> 
> Raox2
> [sparkwerk:master] 1 new commit
> 460c5cd Fixed dev server printing map change messages - Raox2

Dev server appears to be sending messages still. Re-opening for tracking.

**Comment by sunrust-serv** [comment]
Just restarted the dev server, this does not seem to happen
