### ISSUE TITLE
[ZS] Skill description of strengthshot dart gun shows 10s

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#42]
Strength shot dart gun skill shows boost players for 10 seconds.

It's my understanding the dart gun duration was reduced to 6s from 10s. The duration change reduces their utility since there is less of a chance of buffed players using the boost. It limits the usage of dart guns towards in-barricade use only rather than outside the barricade.

One change could be to keep the buff duration of the dart guns at 10 seconds and increase the medical ammo used.

Another option would be to reduce the effectiveness of the buffs (25% extra damage -> lower %/reduce agility boost).

Otherwise if the decrease to 6s is kept then the description of the Strength Dart Gun skill should be changed to 6 seconds.

**Comment by Raox2** [comment]
It was reduced because they were too effective for Tier 1 medical weapons.

**Comment by ritzbits** [comment]
Skill description requires updating

```GM:AddSkill(SKILL_U_STRENGTHSHOT, "Unlock: Strength Dart Gun", GOOD.."Unlocks purchasing the Strength Dart Gun\nTarget damage +25% for 10 seconds\nExtra damage is given to you as points\nTarget is not healed",```
