### ISSUE TITLE
[ZS] Resupply box ammo cache networked later than Ready

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#43]
The resupply appears to be ready, however the cache doesn't appear to exist until a second or so later.

I can't remember the exact issue for late join, but I think it was ready not being networked while the cache is.

**Comment by Raox2** [comment]
It's done this way for performance reasons, but I'll probably take a look and see if I can make it "feel" right.

**Comment by Raox2** [comment]
Can't really do anything about this.
