### ISSUE TITLE
[Sparkwerk] Non-bot maps showing up on MapVote while low player population

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#44]
Main server
![image](https://user-images.githubusercontent.com/10659238/43032898-6d4b8736-8c86-11e8-97e4-bdd80b4a10ae.png)

The humans have WON Zombie Survival (Main Server) on the map zs_last_stand_mall_v5a with 18 humans remaining and 8 zombies.
The humans have LOST Zombie Survival (Main Server) on the map zs_legends_v5 with 18 players. It was wave 4.
zombiesurvival (Main Server) is now playing zs_lost_coast_house_fixed_v2.

Nukkun - Today at 12:30 AM
Last Stand Mall shouldn't be enabled at very low player counts.  It's enormous and there are no bots.  Splitting 16 humans between 5 sigils alternates between extremely dull gameplay and 50% resistance reaming, depending on who gets picked.
Scott - Today at 12:57 AM
it recommended at a very high player count
shouldnt be green if there is a low player count
Nukkun - Today at 1:10 AM
I think there's a case for just disabling maps without navmeshes when the server is under thirty or so players.

**Comment by Raox2** [comment]
That's a bug, it shouldn't be happening. I'll try and fix it. Non-bot maps are only supposed to appear above 40 players right now.

**Comment by ritzbits** [comment]
zs_business_v2 - 6 players : selection of non-bot maps appeared
zs_fog_village_v2  - 15 players : selection of non-bot maps appeared
![image](https://user-images.githubusercontent.com/10659238/45210579-9cf3fc80-b255-11e8-8510-74db6276b78a.png)
zs_ravenstreet_v1 - 16 players
![image](https://user-images.githubusercontent.com/10659238/45210848-4a671000-b256-11e8-8183-fe9e6d443b80.png)

**Comment by ritzbits** [comment]
Raox2
[sparkwerk:master] 2 new commits
9153599 Should be impossible for non-bot maps to appear - Raox2
29a6965 Merge branch 'master' of github.com:Raox2/spark... - Raox
