### ISSUE TITLE
[ZS] No collide sigils

### ISSUE THREAD

**Issue by Jimmyboi55** [Raox2/sunrust-issues#45]
The No collide sigil (unfair for zombies).  Old time bug as I'm sure your aware. It became a much more frequent bug when humans spawned in the sigil at game start. I suspect it is triggered when a human teleports into a sigil with dead zombies inside it. (humans and zombies cannot exist in the same place)  The reason I think this is that we were midway through taking a Sigil  and as a human teleported in, the Sigil started recharging in the no collide state.  Humans and zombies cannot exist in the same spot.  Might copy and paste this in Github bugs.

**Comment by Raox2** [comment]
Should be fixed now.
