### ISSUE TITLE
Chatbox bug: console says upon joining

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#46]
Upon joining the server 1-2 chatbox messages print as console says rather than from players. Minor bug. Needs confirmation.

![image](https://user-images.githubusercontent.com/10659238/43466506-4a5b0bd0-94a5-11e8-9106-79963440dab5.png)

**Comment by ghost** [comment]
I'm pretty sure this is a thing in the default chatbox as well, it happens because the client can receive chat messages before they're initialized.

It can also happen when starting a demo recording.

**Comment by MrCraigTunstall** [comment]
best to use the PlayerReady hook before attempting to send any form of message.
