### ISSUE TITLE
[ZS] func_areaportal doesn't open when ironsighting

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#48]
func_areaportals which are closed at a distance, do not open when zooming in via ironsights.
The issue doesn't occur with the hl2 suit zoom and weapon_crossbow.

------------------

zs_splinter_v2

weapon_zs_crossbow
![20180802215815_1](https://user-images.githubusercontent.com/39219459/43610838-367091f2-969f-11e8-8475-75677adb5a95.jpg)

weapon_crossbow
![20180802215700_1](https://user-images.githubusercontent.com/39219459/43610841-399352c0-969f-11e8-817c-210a96d2cae7.jpg)

**Comment by Raox2** [comment]
I actually don't know if I can do anything about this

**Comment by ghost** [comment]
Would it be classified as an engine issue with [TranslateFOV](https://wiki.garrysmod.com/page/WEAPON/TranslateFOV) ?

**Comment by Raox2** [comment]
Probably. You could check that, I'd imagine it is.

**Comment by ghost** [comment]
Seems to be an issue with sweps that use TranslateFOV, but not with [Player:SetFOV](https://wiki.garrysmod.com/page/Player/SetFOV).

**Comment by ghost** [comment]
Posted: https://github.com/Facepunch/garrysmod-issues/issues/3564

Relevant: https://github.com/Facepunch/garrysmod-requests/issues/1024

**Comment by Raox2** [comment]
Don't think I can do anything with this myself
