### ISSUE TITLE
[ZS] Demiboss notification indicator states you will become demiboss and you will not spawn

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#52]
The demiboss indicator may incorrectly display that _You will become 1 of ... demibosses soon_, and the player does not spawn as demiboss.

Related suggestion to demi_text: change font color from COLOR_GRAY to COLOR_ORANGE (or red) to distinguish text from __There will be ... demibosses soon.__

**Comment by Raox2** [comment]
I have no idea how to fix it. I suspect players are just getting it taken from them last moment.

**Comment by ritzbits** [comment]
Seems like it could be _n_ number of demibosses with n + 1 (player ranked next after the number of demibosses) being shown the message.

Damage rankings
Player 1 will spawn as boss soon
You will spawn as 1 of 3 demibosses soon. (n = 3)
1. Boss
2. Demiboss
3. Demiboss
4. Demiboss
5. Not demiboss (_you will spawn as demiboss_ still shown)

**Comment by Raox2** [comment]
I believe I may have fixed it just recently.

**Comment by ritzbits** [comment]
Confirmed bug is still occurring.

**Comment by ritzbits** [comment]
No longer issue since demiboss system moved to progress bar.
