### ISSUE TITLE
[ZS] Boss zombie collisions

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#54]
Known issue

------------------------

Additional information:

![image](https://user-images.githubusercontent.com/10659238/46335030-d10bd480-c5eb-11e8-8b3b-af97ba0d06fa.png)
zs_gups_abandoned_mall_v2 has a trigger teleport system similar to zs_obj_enervation where players redeem in a certain closed-off location before being teleported to the intended redeem destination. The trigger teleport is a small flat cube located in a closed off area  on the second floor of the anime store reachable only by noclip or through player redeems.

A few players have reported they have been teleporting to the redeem destination as Bonemesh.

Observed Hate great evil teleported multiple times. Likely applies to Shit Slapper. Does not appear to be an issue for any regular-sized zombie classes since no issues were reported.

Unable to replicate locally/dev server. May be an issue with collisions that happens every so often only when server is more populated.

**Comment by ritzbits** [comment]
The teleport issue can be fixed easily by adding a team filter, although the teleportation issue seems related to boss zombies taking random damage from far away.

**Comment by Raox2** [comment]
Very unlikely to be a major issue.
