### ISSUE TITLE
[ZS] Brass Ejections - lowers fps in a number of ways

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#6]
It becomes very noticeable in the late waves, and usually when a lot of ammo is dispensed.

I recreated the event, specifically targeting the effects used in zs, using the emitters tool (shells) in sandbox.
+showbudget shows that brass ejections affect client fps in these following categories.

- Client Animation
- Other Model Rendering
- Light Cache
- Client Simulation
- Prerender
- BuildRenderablesList

Toggling cl_ejectbrass to 0, shows an improvement to fps, and the rendering cost of these categories cut down.
This command however does not work for zs weapons.

I'm aware of the attempt at disabling these in the past were met with unforeseen side effects, I hope this can be looked into again.

**Comment by Raox2** [comment]
For some reason, it disables the muzzle flashes iirc when I used to do it.

**Comment by ghost** [comment]
Can you disable thirdperson muzzle flashes for players who are "shadowman" including being culled from transparency radius.

https://wiki.garrysmod.com/page/WEAPON/FireAnimationEvent

Some muzzle flashes are either too big (Adonis Pulse Rifle) and opaque, it's an annoyance when many players are using the same shooting angles.

The bullet tracer is enough to see if other players are firing, and isn't as obtrusive as the muzzle fires.
