### ISSUE TITLE
[ZS] Shade shield contribution towards boss

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-issues#62]
Boss progress while boss removed in commit
https://github.com/Raox2/sunrust-zs/commit/d7978d793522ff3e04f49693900be32c673937f8

Boss progress while boss re-added in commit (with penalty) - missing shade shield contribution
https://github.com/Raox2/sunrust-zs/commit/732f465cd04bde7f753029d19fab3e817d9c1d07

**Comment by Raox2** [comment]
Keeping it removed for now.
