### ISSUE TITLE
[ZS] Extra checks to unrender other players weapons

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#7]
https://my.mixtape.moe/iepzth.webm

![20180529200938_1](https://user-images.githubusercontent.com/39219459/40680021-b1e0ae68-637c-11e8-8a5f-1a94787dea40.jpg)
![20180529200942_1](https://user-images.githubusercontent.com/39219459/40680023-b4d960f6-637c-11e8-9798-0d82b09854c5.jpg)

An enhancement for SWEP:DrawWorldModel, mainly focuses on weapons with extra models attached.
If the player is culled from an area portal or visleaf, then the weapon and/or the attached models should not render.

Only helps improve perf when the player is culled from view, if you're on the Zombie team, or have a transparency radius set to not cull the players.

Affects
- Other Model Rendering
- GLua
- DrawOpaqueRenderables

**Comment by ghost** [comment]
sck based sweps render the same amount of models for view  and world, this is not optimal for performance:

Suggestions:

- [ ] Limit the amount of props rendered for the swep's world model, to the bare minimum that it can still be distinguished from other sweps.

- [ ] Create a slider option, "Max weapon models rendered" per frame, 0 for unlimited.

Secondary options.
Option 1 to give render priority to weapon models closest to the local player.
Option 2 to spread model count to all drawn weapons.

- [ ] Lower LOD of the world models.

- [x] Disable prop lighting for the world models.
> Raox: Added a new option to disable weapon world models from being lit

----------------------------------------------------------------------------------
### ~~Phase out the Swep Construction Kit~~
~~In a last ditch effort for _performance_, and if this is feasible to accomplish.~~
~~Dump the Swep Construction Kit from the gamemode, only use as a design tool, then have a modeler recreate the weapons and other entities as single models with additional features:~~

~~- High/Medium/Low LODs for view model~~
~~- Lowest LOD for world model~~
~~- Simple physics collision~~
~~- Custom view and world animations~~
~~- Add skins (for variants)~~
~~- Add bodygroups (for variants)~~
~~- Add color (for variants, or for client customization with cl_weaponcolor)~~

~~Not really necessary to do this next one:~~
~~- Keep both sck weapons/entities, and their single model replacements.~~
~~Allow clients to choose whether they want fps or not download extra files.~~

**Comment by ghost** [comment]
I've made a comparison with weapon_zs_boomstick and weapon_shotgun.

weapon_shotgun
![20180607170158_1](https://user-images.githubusercontent.com/39219459/41111760-e5bd8aae-6a74-11e8-97c2-e7c0a55d8049.jpg)

weapon_zs_boomstick is more expensive in DrawOpaqueRenderables.
![20180607170224_1](https://user-images.githubusercontent.com/39219459/41111773-ef568908-6a74-11e8-94e3-3f3b3e2289ed.jpg)

weapon_crowbar
![20180607171515_1](https://user-images.githubusercontent.com/39219459/41112336-8d9e95aa-6a76-11e8-8370-e1dd3a5e36a0.jpg)

weapon_zs_crowbar
![20180607171534_1](https://user-images.githubusercontent.com/39219459/41112340-911967fa-6a76-11e8-9a16-0c183d3c67c1.jpg)

I've tested with weapon_pistol and weapon_zs_owens, same issue present.
They're both opaque, but the zs versions happen to be more expensive.

Edit: I've looked into other weapon bases, it seems to be a quirk of gmod which causes any lua weapons to cost more in DrawOpaqueRenderables.

I've posted it as an issue on gmod issues.
https://github.com/Facepunch/garrysmod-issues/issues/3499

**Comment by Raox2** [comment]
Removing the swep construction kit is virtually insane. The reason it is used is because it allows building weapons with custom models in low time with no downloads.

**Comment by ghost** [comment]
True, which is why I consider it last ditch effort.
I'm more interested into looking for possible improvements to it, as it's an essential tool for the gamemode.

Another test, with prop_weapon:
Dropped several weapon_zs_gluon's and weapon_zs_spinfusor.

![20180607173639_1](https://user-images.githubusercontent.com/39219459/41113451-94b99b84-6a79-11e8-95ec-350bc7e66774.jpg)

r_drawopaquerenderables 0 
Notice how other model rendering is cut in half, and GLua peaks at around 2.5 ms
![20180607173649_1](https://user-images.githubusercontent.com/39219459/41113455-9804deac-6a79-11e8-9b07-0cb9c06bd948.jpg)

so it seems this is just a case of double render in this regard, one for opaque and one for translucent.
Tested with r_drawtranslucentrenderables and r_drawopaquerenderables.

[RENDERGROUP_BOTH](https://wiki.garrysmod.com/page/Enums/RENDERGROUP) creates draw calls for draw and drawtranslucent.

In prop_baseoutlined, it has Ent:Draw and Ent:DrawTranslucent, only Ent:DrawTranslucent is needed.

> [sunrust-zs:master] 1 new commit
3bd8d0b Improved rendering of dropped items - Raox2

**Comment by ghost** [comment]
This may be closed, but I still wish to see the rendering cost of sck weapons cut down or at least considered.
https://github.com/Raox2/sunrust-issues/issues/7#issuecomment-394086830

**Comment by ghost** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1168

Would be useful in this case, if it's added.

**Comment by ghost** [comment]
Would it be possible to cull equipped weapons if the player is blocked in line of sight?

- A player is behind a wall/object
- A player is behind another player

http://wiki.garrysmod.com/page/Entity/Visible

**Comment by Raox2** [comment]
Might be more expensive to check than actually cull it
