### ISSUE TITLE
[ZS] Unnecessary use of SetLighting(true) in lua particle effects

### ISSUE THREAD

**Issue by ghost** [Raox2/sunrust-issues#9]
[particle:SetLighting(true)](https://github.com/JetBoom/zombiesurvival/search?p=1&q=SetLighting%28true%29&unscoped_q=SetLighting%28true%29)

Noticeable with multiple effects computing light at the same time.

Affects Light Cache.

When disabled, particles will become more vibrant in color.
If this is not desirable, it is easily rectifiable with color editing.

**Comment by Raox2** [comment]
Some particles are meant to have light context in their appearance, so this is probably a bit of an art argument. I'll experiment regardless.

**Comment by ghost** [comment]
As long as it isn't required by particles that can be spammed.

**Comment by ghost** [comment]
Can you please provide a list of particles (from effects/status/prop) which were changed?
I want to make sure the change covered all which can be spammed.

**Comment by ghost** [comment]
Was it applied to:

bloodstream
dismemberment
gib_player
gore_blast
particles from prop_playergib

**Comment by Raox2** [comment]
bloodstream - no
dismemberment - yes
gib_player - no
gore_blast - no
particles from prop_playergib - no

I can do those!

**Comment by ghost** [comment]
I think projectile_bonemesh may need this applied along with particle collision disabled for the skull ball, it seems spammable.

The exploding effect with collision is alright.
